### ISSUE TITLE
oneOf within array's items description doesn't seem to validate/work as expected

### ISSUE THREAD

**Issue by gerazenobi** [p1c2u/openapi-core#129]
I have the following query parameter described within a certain path:

```yaml
      parameters:
        - in: query
          name: date
          required: true
          explode: true
          style: form
          schema:
            type: array
            items:
              oneOf:
                - type: string
                  format: date-time
                - type: string
                  pattern: '^now$|^in-(\d+)-(minutes|hours)$'
            example:
              - '2019-04-07T15:30:00.000Z'
              - 'in-60-minutes'
```
Though the parameter values are not being validated as I would expect: I can send any types (string, integer,...) and any format of string ( e.g 'non_valid_format') and the validation won't complaint about it.

Note that for example If I were to specify a homogeneous array (without specifying oneOf) the specified constraints work as expected and I get the expected error messages:

```yaml
      parameters:
        - in: query
          name: date
          required: true
          explode: true
          style: form
          schema:
            type: array
            items:
              type: string
              pattern: '^now$|^in-(\d+)-(minutes|hours)$'
```
Correct response having providing wrong values: 
```
Invalid parameter value for `date`: Value 2019-04-11T10:32:04.662007+00:00 does not match the pattern ^now$|^in-(\d+)-(minutes|hours)$
```

```yaml
      parameters:
        - in: query
          name: date
          required: true
          explode: true
          style: form
          schema:
            type: array
            items:
              type: string
              format: date-time
```
Correct response having provided wrong values:
```
Invalid parameter value for `date`: Failed to format value in-60-minutes to format date-time
```
So my guess is that the problem lies only when using the constraints within a **oneOf** in an array's items section.

I am currently using `openapi-core 0.8.0`
