### ISSUE TITLE
Is there any provision to pickle spec

### ISSUE THREAD

**Issue by jugaadi** [p1c2u/openapi-core#238]

**Comment by playpauseandstop** [comment]
Hi @jugaadi 

Can you provide more details on the topic. Which kind of `pickle` spec provision in `openapi-core` you looking for?

If you need to support serializing / deserializng Python objects via something like,

```yaml
components:
  schemas:
    PickleData:
      type: "string"
      format: "pickle"
```

it in theory possible by providing [custom formatter](https://github.com/playpauseandstop/rororo/blob/3c46dce848d58d4fc665ffcbd304da5854c9ccc0/rororo/openapi/validators.py#L56) to [request](https://github.com/playpauseandstop/rororo/blob/3c46dce848d58d4fc665ffcbd304da5854c9ccc0/rororo/openapi/validators.py#L207) / [response](https://github.com/playpauseandstop/rororo/blob/3c46dce848d58d4fc665ffcbd304da5854c9ccc0/rororo/openapi/validators.py#L228) validator. 

But it may lead into a problems if your OpenAPI schema will be shared with other services, which don't know about given pickle format.

With that in mind, I'd suggest you to do pickle/unpickle by yourself and use binary strings for those data,

```yaml
components:
  schemas:
    BinaryData:
      type: "string"
      format: "binary"
```

[More about media types from OpenAPI docs](https://swagger.io/docs/specification/media-types/)
