### ISSUE TITLE
Enum is not strict

### ISSUE THREAD

**Issue by postalXdude** [p1c2u/openapi-core#255]
```yaml
      - name: calendar_types
        in: query
        style: form
        explode: false
        schema:
          maxItems: 3
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - HOLIDAY
            - BILLING
            - PRICING_PERIOD
```

Hi,

Enum is not working ... at least not validation ... anything can be passed and error will not be raised

version is 0.13.3
