### ISSUE TITLE
Bearer authentication with 'Token' instead of 'Bearer'

### ISSUE THREAD

**Issue by TobiWipf** [p1c2u/openapi-core#317]
Hey! Our authorization header looks like this:
`Authorization: Token <token>`

In the Openapi file the security scheme is specified like
```
securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: 'Authorization:Token <token>'
```

Here is the issue, the `HttpProvider` class responsible for checking the Authentication type just checks against the `scheme` value of `BearerAuth`. Meaning it splits the `bearerFormat` string and looks for the `scheme` value in it and throws an error if it doesn't contain `Bearer`. As far as I can see there is no way around it. Am I missing something or did I discover an issue? Thanks for your help:)
