### ISSUE TITLE
Server urls with variables aren't supported

### ISSUE THREAD

**Issue by domenkozar** [p1c2u/openapi-core#60]
If one has openapiv3 with server urls:

```yaml
  - url: https://app-pr-{prId}.herokuapp.com/api/v1	   
     description: Staging	    
     variables:	
        prId:	
           default: '1'
```

Then using `https://app-pr-56.herokuapp.com/api/v1` will result into
`InvalidServer('Invalid request server https://app-pr-56.herokuapp.com/api/v1/user/login',)`.

Workaround for now is just to skip domain with `url: /api/v1`.
