### ISSUE TITLE
oneOf in array items not working

### ISSUE THREAD

**Issue by smarlowucf** [p1c2u/openapi-core#64]
If you have multiple types (oneOf) of items in an array only the first is validated against:

schema
```
conditions:
  type: array
  items:
    oneOf:
      - type: object
        required:
          - image
        properties:
          image:
            type: string
        additionalProperties: false
      - type: object
        required:
          - package
        properties:
          package:
            type: array
            items:
              type: string
            minItems: 2
```

request
```
{'conditions': [{'image': 'data'}, {'package': ['info', 'data']}]}
```

Yields to exception, invalid schema property 'package'.
