### ISSUE TITLE
oneOf type forced to object

### ISSUE THREAD

**Issue by smarlowucf** [p1c2u/openapi-core#65]
If you have a list oneOf types validator defaults them to object and fails:

schema
```
utctime:
  oneOf:
    - type: string
      enum: [always, now]
    - type: string
      format: date-time
```

request
```
{'utctime': 'now'}
```

Yields, openapi_core.schema.media_types.exceptions.InvalidMediaTypeValue: Value of now not an object.

Now should be of type string not object.
