### ISSUE TITLE
Validation always pass

### ISSUE THREAD

**Issue by rafaelcaricio** [p1c2u/openapi-core#97]
Because of those lines: https://github.com/p1c2u/openapi-core/blob/master/openapi_core/schema/schemas/models.py#L224-L225

Validation always pass. It will fail in the proper object validation, but the exception it caught and `continue` is called, failing silently. Then it validates on boolean type (https://github.com/p1c2u/openapi-core/blob/master/openapi_core/schema/schemas/util.py#L8-L12) because any `dict` with keys is a valid bool `true`. So the value returned is `true` which is not valid by my schema.

**Comment by rafaelcaricio** [comment]
It gives an error if you don't define the `type` field in the JSON schema.
Like:
```
type: array
items:
  allOf:
  - type: object
    properties:
      a:
        type: string
  - type: object
    properties:
      b:
        type: string
```

The validation does not pass, if:
```
type: array
items:
  type: object
  allOf:
  - type: object
    properties:
      a:
        type: string
  - type: object
    properties:
      b:
        type: string
```
